/** Nhóm HV 6 chữ — sinh từ SKU_mapping_HV_10ky_tu_v2.xlsx sheet Ket_qua. */

export type HvIndustryCode =
  | "TA"
  | "VS"
  | "DC"
  | "YT"
  | "TT"
  | "PK"
  | "VT"
  | "DV"
  | "KHAC";

export type HvGroupMeta = {
  title: string;
  industry: HvIndustryCode;
  species: string;
  merch: string;
  spec: string;
};

export const HV_GROUPS: Record<string, HvGroupMeta> = {
  "CCNXXX": { title: "Thực phẩm chức năng — chó", industry: "YT", species: "C", merch: "CN", spec: "XXX" },
  "CDCKVS": { title: "Khay vệ sinh — chó", industry: "PK", species: "C", merch: "DC", spec: "KVS" },
  "CĐCXXX": { title: "Đồ chơi — chó", industry: "DC", species: "C", merch: "ĐC", spec: "XXX" },
  "CĐTTHT": { title: "Thuốc hỗ trợ — chó", industry: "YT", species: "C", merch: "ĐT", spec: "THT" },
  "CĐTXGP": { title: "Tẩy giun / ve — chó", industry: "YT", species: "C", merch: "ĐT", spec: "XGP" },
  "CĐTXNP": { title: "CĐTXNP", industry: "YT", species: "C", merch: "ĐT", spec: "XNP" },
  "CPKAQU": { title: "Áo quần — chó", industry: "TT", species: "C", merch: "PK", spec: "AQU" },
  "CPKTBI": { title: "Tã, bỉm — chó", industry: "PK", species: "C", merch: "PK", spec: "TBI" },
  "CTPCHI": { title: "Thức ăn chính (hạt) — chó", industry: "TA", species: "C", merch: "TP", spec: "CHI" },
  "CTPMIL": { title: "Sữa dinh dưỡng — chó", industry: "TA", species: "C", merch: "TP", spec: "MIL" },
  "CTPPAT": { title: "Pate / thức ăn ướt — chó", industry: "TA", species: "C", merch: "TP", spec: "PAT" },
  "CTPPHU": { title: "Thức ăn phụ khác — chó", industry: "TA", species: "C", merch: "TP", spec: "PHU" },
  "CTPSNK": { title: "Snack / treat / xúc xích — chó", industry: "TA", species: "C", merch: "TP", spec: "SNK" },
  "CVSKMP": { title: "Khử mùi — chó", industry: "VS", species: "C", merch: "VS", spec: "KMP" },
  "CVSMIE": { title: "Vệ sinh miệng / răng — chó", industry: "VS", species: "C", merch: "VS", spec: "MIE" },
  "CVSSTP": { title: "Sữa tắm — chó", industry: "VS", species: "C", merch: "VS", spec: "STP" },
  "CVSTAI": { title: "Vệ sinh tai — chó", industry: "VS", species: "C", merch: "VS", spec: "TAI" },
  "CVTXXX": { title: "Que test — chó", industry: "VT", species: "C", merch: "VT", spec: "XXX" },
  "HCNXXX": { title: "Thực phẩm chức năng — chó và mèo", industry: "YT", species: "H", merch: "CN", spec: "XXX" },
  "HDCANU": { title: "Dụng cụ ăn uống (bát, bình)", industry: "PK", species: "H", merch: "DC", spec: "ANU" },
  "HDCGRO": { title: "Dụng cụ grooming (lược, kìm, tông đơ)", industry: "PK", species: "H", merch: "DC", spec: "GRO" },
  "HDCKVS": { title: "HDCKVS", industry: "PK", species: "H", merch: "DC", spec: "KVS" },
  "HDCXEN": { title: "Xẻng / dụng cụ dọn cát", industry: "PK", species: "H", merch: "DC", spec: "XEN" },
  "HDCXXX": { title: "Dụng cụ khác", industry: "PK", species: "H", merch: "DC", spec: "XXX" },
  "HDVDLC": { title: "DV lưu chuồng", industry: "DV", species: "H", merch: "DV", spec: "DLC" },
  "HDVGRM": { title: "DV grooming / spa", industry: "DV", species: "H", merch: "DV", spec: "GRM" },
  "HDVKCB": { title: "DV khám chữa bệnh", industry: "DV", species: "H", merch: "DV", spec: "KCB" },
  "HDVNHA": { title: "DV nha khoa thú cưng", industry: "DV", species: "H", merch: "DV", spec: "NHA" },
  "HĐCXXX": { title: "Đồ chơi — chó và mèo", industry: "DC", species: "H", merch: "ĐC", spec: "XXX" },
  "HĐTDTP": { title: "Dịch truyền — chó và mèo", industry: "YT", species: "H", merch: "ĐT", spec: "DTP" },
  "HĐTPTP": { title: "Phẫu thuật thú cưng", industry: "YT", species: "H", merch: "ĐT", spec: "PTP" },
  "HĐTSAP": { title: "Siêu âm thú cưng", industry: "YT", species: "H", merch: "ĐT", spec: "SAP" },
  "HĐTTHT": { title: "Thuốc hỗ trợ — chó và mèo", industry: "YT", species: "H", merch: "ĐT", spec: "THT" },
  "HĐTTKS": { title: "Kháng sinh — chó và mèo", industry: "YT", species: "H", merch: "ĐT", spec: "TKS" },
  "HĐTVAC": { title: "Vắc xin — chó và mèo", industry: "YT", species: "H", merch: "ĐT", spec: "VAC" },
  "HĐTXGP": { title: "Tẩy giun / ve — chó và mèo", industry: "YT", species: "H", merch: "ĐT", spec: "XGP" },
  "HĐTXNP": { title: "Xét nghiệm thú cưng", industry: "YT", species: "H", merch: "ĐT", spec: "XNP" },
  "HĐTXQP": { title: "X-quang thú cưng", industry: "YT", species: "H", merch: "ĐT", spec: "XQP" },
  "HĐTXXX": { title: "Điều trị khác", industry: "YT", species: "H", merch: "ĐT", spec: "XXX" },
  "HHCXNM": { title: "HHCXNM", industry: "KHAC", species: "H", merch: "HC", spec: "XNM" },
  "HPKAQU": { title: "Áo quần — chó và mèo", industry: "TT", species: "H", merch: "PK", spec: "AQU" },
  "HPKBLO": { title: "Balo, túi xách, địu (balo)", industry: "PK", species: "H", merch: "PK", spec: "BLO" },
  "HPKDAY": { title: "Dây dắt", industry: "PK", species: "H", merch: "PK", spec: "DAY" },
  "HPKDIU": { title: "Địu thú cưng", industry: "PK", species: "H", merch: "PK", spec: "DIU" },
  "HPKNNE": { title: "Nhà, nệm", industry: "PK", species: "H", merch: "PK", spec: "NNE" },
  "HPKRLO": { title: "Rọ mõm, loa chống liếm", industry: "PK", species: "H", merch: "PK", spec: "RLO" },
  "HPKTBI": { title: "Tã, bỉm, miếng lót", industry: "PK", species: "H", merch: "PK", spec: "TBI" },
  "HPKTTR": { title: "Thời trang (nón, giày, vớ)", industry: "TT", species: "H", merch: "PK", spec: "TTR" },
  "HPKTXA": { title: "Túi xách", industry: "PK", species: "H", merch: "PK", spec: "TXA" },
  "HPKVCO": { title: "Vòng cổ", industry: "PK", species: "H", merch: "PK", spec: "VCO" },
  "HTPCHI": { title: "Thức ăn chính (hạt) — chó và mèo", industry: "TA", species: "H", merch: "TP", spec: "CHI" },
  "HTPMIL": { title: "Sữa dinh dưỡng — chó và mèo", industry: "TA", species: "H", merch: "TP", spec: "MIL" },
  "HTPPAT": { title: "Pate / thức ăn ướt — chó và mèo", industry: "TA", species: "H", merch: "TP", spec: "PAT" },
  "HTPSNK": { title: "Snack / treat — chó và mèo", industry: "TA", species: "H", merch: "TP", spec: "SNK" },
  "HTPSUP": { title: "Súp thưởng — chó và mèo", industry: "TA", species: "H", merch: "TP", spec: "SUP" },
  "HVCXXX": { title: "Lồng vận chuyển — chó và mèo", industry: "PK", species: "H", merch: "VC", spec: "XXX" },
  "HVSKMP": { title: "Khử mùi — chó và mèo", industry: "VS", species: "H", merch: "VS", spec: "KMP" },
  "HVSMAT": { title: "Vệ sinh mắt — chó và mèo", industry: "VS", species: "H", merch: "VS", spec: "MAT" },
  "HVSMIE": { title: "Vệ sinh miệng / răng — chó và mèo", industry: "VS", species: "H", merch: "VS", spec: "MIE" },
  "HVSMTX": { title: "Sát trùng môi trường", industry: "VS", species: "H", merch: "VS", spec: "MTX" },
  "HVSNHP": { title: "Nước hoa thú cưng", industry: "VS", species: "H", merch: "VS", spec: "NHP" },
  "HVSSTP": { title: "Sữa tắm — chó và mèo", industry: "VS", species: "H", merch: "VS", spec: "STP" },
  "HVSTAI": { title: "Vệ sinh tai — chó và mèo", industry: "VS", species: "H", merch: "VS", spec: "TAI" },
  "HVSXXX": { title: "Vệ sinh khác — chó và mèo", industry: "VS", species: "H", merch: "VS", spec: "XXX" },
  "HVTGON": { title: "HVTGON", industry: "VT", species: "H", merch: "VT", spec: "GON" },
  "HVTGTP": { title: "HVTGTP", industry: "VT", species: "H", merch: "VT", spec: "GTP" },
  "HVTGTX": { title: "HVTGTX", industry: "VT", species: "H", merch: "VT", spec: "GTX" },
  "HVTKCB": { title: "HVTKCB", industry: "VT", species: "H", merch: "VT", spec: "KCB" },
  "HVTKIB": { title: "HVTKIB", industry: "VT", species: "H", merch: "VT", spec: "KIB" },
  "HVTKIL": { title: "HVTKIL", industry: "VT", species: "H", merch: "VT", spec: "KIL" },
  "HVTKIM": { title: "HVTKIM", industry: "VT", species: "H", merch: "VT", spec: "KIM" },
  "HVTKIN": { title: "HVTKIN", industry: "VT", species: "H", merch: "VT", spec: "KIN" },
  "HVTKSĐ": { title: "Kháng sinh đồ / đĩa xét nghiệm", industry: "VT", species: "H", merch: "VT", spec: "KSĐ" },
  "HVTNKQ": { title: "HVTNKQ", industry: "VT", species: "H", merch: "VT", spec: "NKQ" },
  "HVTPTA": { title: "HVTPTA", industry: "VT", species: "H", merch: "VT", spec: "PTA" },
  "HVTPTC": { title: "HVTPTC", industry: "VT", species: "H", merch: "VT", spec: "PTC" },
  "HVTPTG": { title: "HVTPTG", industry: "VT", species: "H", merch: "VT", spec: "PTG" },
  "HVTPTK": { title: "HVTPTK", industry: "VT", species: "H", merch: "VT", spec: "PTK" },
  "HVTPTN": { title: "HVTPTN", industry: "VT", species: "H", merch: "VT", spec: "PTN" },
  "HVTPTS": { title: "HVTPTS", industry: "VT", species: "H", merch: "VT", spec: "PTS" },
  "HVTTHO": { title: "HVTTHO", industry: "VT", species: "H", merch: "VT", spec: "THO" },
  "HVTXNC": { title: "HVTXNC", industry: "VT", species: "H", merch: "VT", spec: "XNC" },
  "HVTXNM": { title: "HVTXNM", industry: "VT", species: "H", merch: "VT", spec: "XNM" },
  "HVTXXX": { title: "Vật tư / que test khác", industry: "VT", species: "H", merch: "VT", spec: "XXX" },
  "MCAXXX": { title: "Cát vệ sinh — mèo", industry: "VS", species: "M", merch: "CA", spec: "XXX" },
  "MCNXXX": { title: "Thực phẩm chức năng — mèo", industry: "YT", species: "M", merch: "CN", spec: "XXX" },
  "MDCANU": { title: "Dụng cụ ăn uống — mèo", industry: "PK", species: "M", merch: "DC", spec: "ANU" },
  "MDCKVS": { title: "Khay vệ sinh — mèo", industry: "PK", species: "M", merch: "DC", spec: "KVS" },
  "MDCXEN": { title: "Xẻng — mèo", industry: "PK", species: "M", merch: "DC", spec: "XEN" },
  "MĐCXXX": { title: "Đồ chơi — mèo", industry: "DC", species: "M", merch: "ĐC", spec: "XXX" },
  "MĐTTHT": { title: "Thuốc hỗ trợ — mèo", industry: "YT", species: "M", merch: "ĐT", spec: "THT" },
  "MĐTXGP": { title: "Tẩy giun / ve — mèo", industry: "YT", species: "M", merch: "ĐT", spec: "XGP" },
  "MĐTXNP": { title: "MĐTXNP", industry: "YT", species: "M", merch: "ĐT", spec: "XNP" },
  "MPKAQU": { title: "Áo quần — mèo", industry: "TT", species: "M", merch: "PK", spec: "AQU" },
  "MPKNNE": { title: "MPKNNE", industry: "PK", species: "M", merch: "PK", spec: "NNE" },
  "MTPCHI": { title: "Thức ăn chính (hạt) — mèo", industry: "TA", species: "M", merch: "TP", spec: "CHI" },
  "MTPMIL": { title: "Sữa dinh dưỡng — mèo", industry: "TA", species: "M", merch: "TP", spec: "MIL" },
  "MTPPAT": { title: "Pate / thức ăn ướt — mèo", industry: "TA", species: "M", merch: "TP", spec: "PAT" },
  "MTPPHU": { title: "Thức ăn phụ khác — mèo", industry: "TA", species: "M", merch: "TP", spec: "PHU" },
  "MTPSNK": { title: "Snack / treat — mèo", industry: "TA", species: "M", merch: "TP", spec: "SNK" },
  "MTPSUP": { title: "Súp thưởng — mèo", industry: "TA", species: "M", merch: "TP", spec: "SUP" },
  "MVCXXX": { title: "Lồng vận chuyển — mèo", industry: "PK", species: "M", merch: "VC", spec: "XXX" },
  "MVSKMP": { title: "Khử mùi — mèo", industry: "VS", species: "M", merch: "VS", spec: "KMP" },
  "MVSMIE": { title: "Vệ sinh miệng / răng — mèo", industry: "VS", species: "M", merch: "VS", spec: "MIE" },
  "MVSSTP": { title: "Sữa tắm — mèo", industry: "VS", species: "M", merch: "VS", spec: "STP" },
};
