// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
// Prefer publishable/anon key. Never use sb_secret_* in the browser (causes 401).
const rawKey =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;
const fallbackPublishable = import.meta.env.VITE_SUPABASE_PUBLISHABLE_DEFAULT_KEY;
const SUPABASE_PUBLISHABLE_KEY =
  typeof rawKey === "string" && rawKey.startsWith("sb_secret_")
    ? fallbackPublishable || rawKey
    : rawKey;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabase;
try {
  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const errorMsg = `Missing Supabase credentials: URL=${!!SUPABASE_URL}, KEY=${!!SUPABASE_PUBLISHABLE_KEY}`;
    throw new Error(errorMsg);
  }
  
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY,
      },
    },
  });
} catch (error) {
  if (process.env.NODE_ENV === 'development') {
    console.error("Failed to create Supabase client:", error);
  }
  throw error;
}

export { supabase };